CREATE DATABASE IF NOT EXISTS SPOTIFY;
USE SPOTIFY;

CREATE TABLE ARTISTA(
    ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255),
    COGNOME VARCHAR(255),
    NOTE_BIOGRAFICHE VARCHAR(255),
    NAZIONALITA VARCHAR(255)
);

CREATE TABLE BRANO(
    ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    TITOLO VARCHAR(255),
    DURATA INT(1)
);

CREATE TABLE REGISTRAZIONE(
    ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    TITOLO VARCHAR(255),
    FORMATO VARCHAR(255),
    GENERE VARCHAR(255),
    NOTE VARCHAR(255),
    COSTO DECIMAL(10, 2),
    IDARTISTA INT(11),
    FOREIGN KEY (IDARTISTA) REFERENCES ARTISTA(ID)
    on update cascade
    on delete cascade
);

CREATE TABLE INTERPRETARE(
    ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    IDBRANO INT(11),
    FOREIGN KEY (IDBRANO) REFERENCES BRANO(ID)
    on update cascade
    on delete cascade,
    IDREGISTRAZIONE INT(11),
    FOREIGN KEY (IDREGISTRAZIONE) REFERENCES REGISTRAZIONE(ID)
    on update cascade
    on delete cascade
);


